# Generated by Django 5.2.7 on 2026-04-03 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchImport',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Import Id')),
                ('date_imported', models.DateTimeField(auto_now_add=True, verbose_name='Date Imported')),
            ],
            options={
                'db_table': 'batch_import',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='batch_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.batchimport'),
        ),
    ]
