# Generated by Django 6.0.3 on 2026-05-13 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrerequisiteMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Prerequisite Map Id')),
            ],
            options={
                'db_table': 'prerequisite_map',
            },
        ),
        migrations.CreateModel(
            name='PrerequisiteMapCourses',
            fields=[
                ('map_entry_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Prerequisite Map Courses Id')),
            ],
            options={
                'db_table': 'prerequisite_map_courses',
            },
        ),
        migrations.RemoveConstraint(
            model_name='applicationprereqmapping',
            name='CPK_application_prereq_mapping',
        ),
        migrations.RemoveField(
            model_name='prereqmapping',
            name='target_course',
        ),
        migrations.RemoveConstraint(
            model_name='prereqmappingcourse',
            name='CPK_prereq_mapping_course',
        ),
        migrations.AddField(
            model_name='prerequisitemap',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
        migrations.AddField(
            model_name='prerequisitemap',
            name='target_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='prerequisitemapcourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='prerequisitemapcourses',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.prerequisitemap'),
        ),
        migrations.RemoveField(
            model_name='applicationprereqmapping',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationprereqmapping',
            name='mapping',
        ),
        migrations.RemoveField(
            model_name='prereqmappingcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='prereqmappingcourse',
            name='mapping',
        ),
        migrations.AddConstraint(
            model_name='prerequisitemapcourses',
            constraint=models.UniqueConstraint(fields=('map', 'course'), name='CPK_prerequisite_map_courses'),
        ),
        migrations.DeleteModel(
            name='ApplicationPrereqMapping',
        ),
        migrations.DeleteModel(
            name='PrereqMapping',
        ),
        migrations.DeleteModel(
            name='PrereqMappingCourse',
        ),
    ]
