# Generated by Django 6.0.3 on 2026-06-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_prerequisitemap_prerequisitemapcourses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtranscript',
            name='grade',
            field=models.CharField(max_length=15, verbose_name='Grade'),
        ),
    ]
