# Generated by Django 5.2.7 on 2026-04-18 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_batchimport_application_batch_import'),
        ('courses', '0004_remove_course_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrereqMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_mapping_targets', to='courses.course')),
            ],
            options={
                'db_table': 'prereq_mapping',
            },
        ),
        migrations.CreateModel(
            name='ApplicationPrereqMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_mappings', to='applications.application')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_usages', to='applications.prereqmapping')),
            ],
            options={
                'db_table': 'application_prereq_mapping',
                'constraints': [models.UniqueConstraint(fields=('application', 'mapping'), name='CPK_application_prereq_mapping')],
            },
        ),
        migrations.CreateModel(
            name='PrereqMappingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_courses', to='applications.prereqmapping')),
            ],
            options={
                'db_table': 'prereq_mapping_course',
                'constraints': [models.UniqueConstraint(fields=('mapping', 'course'), name='CPK_prereq_mapping_course')],
            },
        ),
    ]
