# Generated by Django 6.0.3 on 2026-06-07 16:35

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicationtranscript_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='graduate_failed_subjects',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Graduate Number of Failed Subjects'),
        ),
        migrations.AddField(
            model_name='application',
            name='graduate_gwa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Graduate GWA'),
        ),
        migrations.AddField(
            model_name='application',
            name='ngse_remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NGSE Remarks'),
        ),
        migrations.AddField(
            model_name='application',
            name='ngse_requirements_complete',
            field=models.BooleanField(default=False, verbose_name='NGSE Requirements Complete'),
        ),
        migrations.AddField(
            model_name='application',
            name='research_field_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Research Field 1'),
        ),
        migrations.AddField(
            model_name='application',
            name='research_field_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Research Field 2'),
        ),
        migrations.AddField(
            model_name='application',
            name='research_field_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Research Field 3'),
        ),
        migrations.AddField(
            model_name='application',
            name='special_project_topic_interest',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Special Project Topic Interest'),
        ),
        migrations.AddField(
            model_name='application',
            name='undergraduate_failed_subjects',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Undergraduate Number of Failed Subjects'),
        ),
        migrations.AddField(
            model_name='application',
            name='undergraduate_gwa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Undergraduate GWA'),
        ),
        migrations.AddField(
            model_name='application',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='applicationtranscript',
            name='academic_year',
            field=common.fields.YearField(max_year=2036, min_year=1970, verbose_name='Academic Year'),
        ),
    ]
