# Generated by Django 6.0.3 on 2026-06-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_graduate_failed_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ngse_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='NGSE Remarks'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ngse_requirements_complete',
            field=models.BooleanField(blank=True, null=True, verbose_name='NGSE Requirements Complete'),
        ),
    ]
