# Generated by Django 6.0.3 on 2026-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_ngse_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ngse_requirements_complete',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='NGSE Requirements Complete'),
        ),
    ]
