# Generated by Django 6.0.3 on 2026-06-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_ngse_requirements_complete'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationtranscript',
            name='CPK_application_transcript',
        ),
    ]
