# Generated by Django 6.0.3 on 2026-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_remove_applicationtranscript_cpk_application_transcript'),
        ('courses', '0002_course_notes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applicationtranscript',
            constraint=models.UniqueConstraint(fields=('application', 'course'), name='CPK_application_transcript'),
        ),
    ]
