# Generated by Django 6.0.3 on 2026-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_applicationtranscript_cpk_application_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateTimeField(verbose_name='Date Applied'),
        ),
    ]
