services:
  web:
    build: .
    image: gsas-dockerimg:latest
    container_name: gsas_web
    ports:
      - "${APP_PORT}:8000"
    environment:
      DEBUG: ${DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
    depends_on: {}
    volumes:
      - .:/app
    stdin_open: true
    tty: true

