# Generated by Django 6.0.3 on 2026-04-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Applicant Id')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('applicant_status', models.CharField(choices=[('Applying', 'Applying'), ('Rejected', 'Rejected'), ('Enrolled', 'Enrolled'), ('Deferred', 'Deferred')], max_length=8, verbose_name='Applicant Status')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
    ]
