# Generated by Django 5.2.7 on 2026-03-30 13:52

import applicants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Applicant Id')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('applicant_status', models.CharField(choices=[('applying', 'applying'), ('rejected', 'rejected'), ('enrolled', 'enrolled'), ('deferred', 'deferred')], max_length=8, verbose_name='Applicant Status')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Application Id')),
                ('application_number', models.CharField(max_length=20, verbose_name='Application Number')),
                ('application_status', models.CharField(choices=[('processing', 'processing'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=10, verbose_name='Applicant Status')),
                ('date_applied', models.DateField(verbose_name='Date Applied')),
                ('program', models.CharField(choices=[('PhD CS', 'PhD CS'), ('MS CS', 'MS CS'), ('MS Bioinfo', 'MS Bioinfo')], max_length=10, verbose_name='Degree Program')),
                ('folder_link', models.CharField(max_length=255, verbose_name='Folder Link')),
                ('study_load', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=9, verbose_name='Study Load')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='ApplicationTranscript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Application Transcript Id')),
                ('academic_year', applicants.models.YearField(max_year=2036, min_year=1900, verbose_name='Academic Year')),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=3, verbose_name='Semester')),
                ('grade', models.CharField(choices=[('1.00', '1.00'), ('1.25', '1.25'), ('1.50', '1.50'), ('1.75', '1.75'), ('2.00', '2.00'), ('2.25', '2.25'), ('2.50', '2.50'), ('2.75', '2.75'), ('3.00', '3.00'), ('4.00', '4.00'), ('5.00', '5.00'), ('INC', 'INC'), ('DRP', 'DRP')], max_length=4, verbose_name='Grade')),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='applicants.application')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'db_table': 'application_transcript',
            },
        ),
    ]
