# Generated by Django 6.0.3 on 2026-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Middle Name'),
        ),
    ]
