# Generated by Django 5.2.7 on 2026-04-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_status',
            field=models.CharField(choices=[('applying', 'Applying'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('deferred', 'Deferred')], max_length=8, verbose_name='Applicant Status'),
        ),
    ]
