# Generated by Django 6.0.3 on 2026-04-27 06:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course Id')),
                ('course_code', models.CharField(max_length=20, verbose_name='Course Code')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('units', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Units')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('programs', models.ManyToManyField(related_name='courses', to='programs.program')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='EquivalenceMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='EquivalenceMap Id')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'db_table': 'equivalence_map',
            },
        ),
        migrations.CreateModel(
            name='EquivalenceMapCourses',
            fields=[
                ('map_entry_id', models.AutoField(primary_key=True, serialize=False, verbose_name='EequivalenceMapCourses Id')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.equivalencemap')),
            ],
            options={
                'db_table': 'equivalence_map_courses',
                'constraints': [models.UniqueConstraint(fields=('map', 'course'), name='CPK_equivalence_map_courses')],
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('prereq_entry_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Prereq Entry Id')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_id', to='courses.course', verbose_name='Prereq ID')),
            ],
            options={
                'db_table': 'prerequisite',
                'constraints': [models.UniqueConstraint(fields=('course', 'prereq'), name='CPK_prerequisite')],
            },
        ),
    ]
