# Generated by Django on 2026-04-16

from django.db import migrations

def copy_program_to_programs(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    for course in Course.objects.all():
        if course.program_id:
            course.programs.add(course.program_id)

def backward(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    for course in Course.objects.all():
        if course.programs.exists():
            course.program_id = course.programs.first().pk
            course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_programs'),
    ]

    operations = [
        migrations.RunPython(copy_program_to_programs, backward),
    ]
