# Generated by Django 5.2.7 on 2026-04-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_copy_course_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
    ]
