# Generated by Django 6.0.3 on 2026-04-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False, verbose_name='School Id')),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name')),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
