# Generated by Django 6.0.3 on 2026-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='School Name'),
        ),
    ]
