# Generated by Django 5.2.7 on 2026-03-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Program Id')),
                ('program_name', models.CharField(max_length=50, verbose_name='Program Name')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'db_table': 'program',
            },
        ),
    ]
