# Generated by Django 6.0.3 on 2026-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Program Name'),
        ),
    ]
