# Generated by Django 6.0.3 on 2026-06-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_description_alter_program_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Program Name'),
        ),
    ]
