# Generated by Django 5.2.7 on 2026-02-11 04:28

import database_management.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.CharField(db_column='applicant_id', max_length=20, primary_key=True, serialize=False, verbose_name='Applicant Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('applicant_status', models.CharField(choices=[('applying', 'applying'), ('rejected', 'rejected'), ('enrolled', 'enrolled'), ('deferred', 'deferred')], max_length=8, verbose_name='Applicant Status')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Course ID')),
                ('course_code', models.CharField(max_length=20, verbose_name='Course Code')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('units', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20)], verbose_name='Units')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Program ID')),
                ('program_name', models.CharField(max_length=50, verbose_name='Program Name')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='School ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name')),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.CharField(db_column='application_id', max_length=20, primary_key=True, serialize=False, verbose_name='Application Number')),
                ('application_status', models.CharField(choices=[('processing', 'processing'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=10, verbose_name='Applicant Status')),
                ('date_applied', models.DateField(verbose_name='Date Applied')),
                ('program', models.CharField(choices=[('PhD CS', 'PhD CS'), ('MS CS', 'MS CS'), ('MS Bioinfo', 'MS Bioinfo')], max_length=10, verbose_name='Degree Program')),
                ('folder_link', models.CharField(max_length=255, verbose_name='Folder Link')),
                ('study_load', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=9, verbose_name='Study Load')),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='database_management.applicant')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('enrolled_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Enrolled ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.applicant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.course')),
            ],
            options={
                'db_table': 'enrolled',
            },
        ),
        migrations.CreateModel(
            name='EquivalenceGroup',
            fields=[
                ('group_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Group ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.course')),
            ],
            options={
                'db_table': 'equivalence_groups',
            },
        ),
        migrations.CreateModel(
            name='EquivalenceGroupMap',
            fields=[
                ('map_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Map ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.equivalencegroup')),
            ],
            options={
                'db_table': 'equivalence_group_map',
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('prereq_entry_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='prereq_entry_id')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_id', to='database_management.course', verbose_name='Prereq ID')),
            ],
            options={
                'db_table': 'prerequisite',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.school'),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_entry_id', models.CharField(db_column='transcript_entry_id', max_length=20, primary_key=True, serialize=False, verbose_name='Transcript ID')),
                ('academic_year', database_management.models.YearField(max_year=2036, min_year=1900, verbose_name='Academic Year')),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=3, verbose_name='Semester')),
                ('grade', models.CharField(choices=[('1.00', '1.00'), ('1.25', '1.25'), ('1.50', '1.50'), ('1.75', '1.75'), ('2.00', '2.00'), ('2.25', '2.25'), ('2.50', '2.50'), ('2.75', '2.75'), ('3.00', '3.00'), ('4.00', '4.00'), ('5.00', '5.00'), ('INC', 'INC'), ('DRP', 'DRP')], max_length=4, verbose_name='Grade')),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='database_management.application')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.course')),
            ],
            options={
                'db_table': 'transcript',
            },
        ),
    ]
