# Generated by Django 5.2.7 on 2025-12-10 17:07

import database_management.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Course ID')),
                ('course_code', models.CharField(max_length=20, verbose_name='Course Code')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('units', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20)], verbose_name='Units')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Program ID')),
                ('program_name', models.CharField(max_length=50, verbose_name='Program Name')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='School ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name')),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Student Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('ay_entry', database_management.models.YearField(max_year=2035, min_year=1900, verbose_name='AY Entry')),
                ('ay_latest', database_management.models.YearField(max_year=2035, min_year=1900, verbose_name='AY Latest')),
                ('degree', models.CharField(choices=[('PhD CS', 'PhD CS'), ('MS CS', 'MS CS'), ('MS Bioinfo', 'MS Bioinfo')], max_length=10, verbose_name='Degree Program')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('study_load', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=9, verbose_name='Study Load')),
                ('scholarship', models.CharField(max_length=50, verbose_name='Scholarship')),
                ('progress_status', models.CharField(choices=[('Probationary', 'Probationary'), ('Pre-Proposal', 'Pre-Proposal'), ('Thesis Proposal', 'Thesis Proposal'), ('Thesis Defense', 'Thesis Defense'), ('Candidacy', 'Candidacy'), ('Qualifying Exam', 'Qualifying Exam'), ('Dissertation Proposal', 'Dissertation Proposal'), ('Dissertation Defense', 'Dissertation Defense'), ('Graduate', 'Graduate'), ('Discontinued Program', 'Discontinued Program')], max_length=21, verbose_name='Progress Status')),
                ('year_graduation', database_management.models.YearField(max_year=2035, min_year=1900, verbose_name='Year of Graduation')),
                ('progress_link', models.CharField(max_length=255, verbose_name='Progress Link')),
                ('adviser_lab', models.CharField(max_length=100, verbose_name='Adviser / Lab')),
                ('folder_link', models.CharField(max_length=255, verbose_name='Folder Link')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_id', to='database_management.course', verbose_name='Prereq ID')),
            ],
            options={
                'db_table': 'prerequisite',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.school'),
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.student')),
            ],
            options={
                'db_table': 'enrolled',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Transcript ID')),
                ('academic_year', database_management.models.YearField(max_year=2035, min_year=1900, verbose_name='Academic Year')),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=3, verbose_name='Semester')),
                ('grade', models.CharField(choices=[('1.00', '1.00'), ('1.25', '1.25'), ('1.50', '1.50'), ('1.75', '1.75'), ('2.00', '2.00'), ('2.25', '2.25'), ('2.50', '2.50'), ('2.75', '2.75'), ('3.00', '3.00'), ('4.00', '4.00'), ('5.00', '5.00'), ('INC', 'INC'), ('DRP', 'DRP')], max_length=4, verbose_name='Grade')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.student')),
            ],
            options={
                'db_table': 'transcript',
            },
        ),
    ]
