# Generated by Django 5.2.7 on 2026-02-16 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='applicants_pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF Upload'),
        ),
    ]
