# Generated by Django 5.2.7 on 2026-02-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0002_applicant_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TORText',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database_management.applicant')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'tor_text',
            },
        ),
    ]
