# Generated by Django 5.2.7 on 2026-03-02 16:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course Id')),
                ('course_code', models.CharField(max_length=20, verbose_name='Course Code')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('units', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20)], verbose_name='Units')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Program Id')),
                ('program_name', models.CharField(max_length=50, verbose_name='Program Name')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False, verbose_name='School Id')),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name')),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='EquivalenceGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='EquivalenceGroup Id')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
            options={
                'db_table': 'equivalence_groups',
            },
        ),
        migrations.CreateModel(
            name='EquivalenceGroupMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='EquivalenceGroupMap Id')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.equivalencegroup')),
            ],
            options={
                'db_table': 'equivalence_group_map',
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('prereq_entry_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Prereq Entry Id')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_id', to='academics.course', verbose_name='Prereq ID')),
            ],
            options={
                'db_table': 'prerequisite',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.school'),
        ),
    ]
