# Generated by Django 5.2.7 on 2025-11-05 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Prereqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=14)),
                ('core_course_code', models.CharField(max_length=50)),
                ('prereq_course_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'prereqs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('idstudent', models.AutoField(db_column='idStudent', primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=12, null=True)),
                ('sex', models.CharField(blank=True, max_length=6, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=10, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('years_attended', models.CharField(blank=True, max_length=20, null=True)),
                ('degree_title', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Transcripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_profiles.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_profiles.student')),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
    ]
