# Generated by Django 5.2.7 on 2025-11-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('PhD CS', 'PhD CS'), ('MS CS', 'MS CS'), ('MS Bioinfo', 'MS Bioinfo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='progress_status',
            field=models.CharField(choices=[('Probationary', 'Probationary'), ('Pre-Proposal', 'Pre-Proposal'), ('Thesis Proposal', 'Thesis Proposal'), ('Thesis Defense', 'Thesis Defense'), ('Candidacy', 'Candidacy'), ('Qualifying Exam', 'Qualifying Exam'), ('Dissertation Proposal', 'Dissertation Proposal'), ('Dissertation Defense', 'Dissertation Defense'), ('Graduate', 'Graduate'), ('Discontinued Program', 'Discontinued Program')], max_length=21),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_load',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=9),
        ),
    ]
